version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt update && apt install -y wget git
      - run:
          name: Get mdbook
          command: |
            wget https://github.com/rust-lang-nursery/mdBook/releases/download/v0.1.5/mdbook-v0.1.5-x86_64-unknown-linux-gnu.tar.gz
            tar -xf mdbook-v0.1.5-x86_64-unknown-linux-gnu.tar.gz && rm -f mdbook-v0.1.5-x86_64-unknown-linux-gnu.tar.gz
            mv mdbook /usr/bin/
            mdbook build
            git config --global user.email "vnlabs.org@gmail.com"
            git config --global user.name "VNLabs CI"
            mkdir /tmp/builded_book
            mv book /tmp/builded_book
            cd /tmp/builded_book/book
      - run:
          name: Public the site
          command: |
            scp -i ~/.ssh/${SSH_KEY} -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -P${SSH_PORT} -r * ${SSH_USER}@${SSH_HOST}:${SSH_VNLABS_DIR}
